#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-$(CONFIG_MTK_LENS_FM50AF_SUPPORT)    +=  mt6580/fm50af/
obj-$(CONFIG_MTK_LENS_DW9814AF_SUPPORT)      += mt6580/dw9814af/
obj-$(CONFIG_MTK_LENS_DW9714AF_SUPPORT)      += mt6580/dw9714af/
#obj-y += sensordriver/sensordrive_lens.o




